### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by sol50** [DanMcLaughlin/antlr4cpp#49]
This appears to be a "semi official" attempt at a C++ target. The very existence may mean that other people are discouraged from working on this problem.

If you are no longer working on it, please let us know!

**Comment by sol50** [comment]
And by "working on it", I mean to such a degree that we can expect results within a few months...

**Comment by mike-lischke** [comment]
The development has been moved to the[ antlr4 clone](https://github.com/DanMcLaughlin/antlr4)

**Comment by sol50** [comment]
Thanks!
